"""m4: assets

Revision ID: 4fb3d28300ef
Revises: a2fa00deff17
Create Date: 2026-09-04 08:19:58.867806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4fb3d28300ef'
down_revision: Union[str, Sequence[str], None] = 'a2fa00deff17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Enum('image', 'clip', 'audio', 'video', 'subtitle', 'poster', name='asset_kind'), nullable=False),
    sa.Column('source', sa.Enum('generated', 'manual', 'derived', name='asset_source'), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=80), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('has_audio', sa.Boolean(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_cents', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_assets_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assets'))
    )
    op.create_index('ix_assets_input_hash', 'assets', ['input_hash'], unique=False)
    op.create_index('ix_assets_project_kind', 'assets', ['project_id', 'kind', 'created_at'], unique=False)
    op.create_foreign_key(op.f('fk_characters_reference_asset_id_assets'), 'characters', 'assets', ['reference_asset_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_narration_lines_audio_asset_id_assets'), 'narration_lines', 'assets', ['audio_asset_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_shots_selected_clip_id_assets'), 'shots', 'assets', ['selected_clip_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_shots_selected_image_id_assets'), 'shots', 'assets', ['selected_image_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_constraint(op.f('fk_shots_selected_image_id_assets'), 'shots', type_='foreignkey')
    op.drop_constraint(op.f('fk_shots_selected_clip_id_assets'), 'shots', type_='foreignkey')
    op.drop_constraint(op.f('fk_narration_lines_audio_asset_id_assets'), 'narration_lines', type_='foreignkey')
    op.drop_constraint(op.f('fk_characters_reference_asset_id_assets'), 'characters', type_='foreignkey')
    op.drop_index('ix_assets_project_kind', table_name='assets')
    op.drop_index('ix_assets_input_hash', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
