"""m5: project voice and music

Revision ID: 5c272053b67a
Revises: 96336d64c308
Create Date: 2026-09-04 08:46:01.278792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c272053b67a'
down_revision: Union[str, Sequence[str], None] = '96336d64c308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('narrator_voice_id', sa.String(length=40), nullable=True))
    op.add_column('projects', sa.Column('music_track_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'music_track_key')
    op.drop_column('projects', 'narrator_voice_id')
    # ### end Alembic commands ###
