"""initial: users and projects

Revision ID: 7d49906e4c14
Revises: 
Create Date: 2026-09-01 01:11:28.725417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d49906e4c14'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('projects',
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('stage', sa.Enum('draft', 'analyzed', 'storyboarded', 'characters_locked', 'stills', 'narration', 'previewed', 'motion', 'rendered', name='project_stage'), nullable=False),
    sa.Column('aspect_ratio', sa.String(length=12), nullable=False),
    sa.Column('image_size', sa.String(length=20), nullable=False),
    sa.Column('style_preset', sa.String(length=60), nullable=False),
    sa.Column('style_bible', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('default_model_key', sa.String(length=64), nullable=True),
    sa.Column('allow_premium', sa.Boolean(), nullable=False),
    sa.Column('budget_cents', sa.Integer(), nullable=False),
    sa.Column('spent_cents', sa.Integer(), nullable=False),
    sa.Column('share_token', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('budget_cents >= 0', name=op.f('ck_projects_budget_nonnegative')),
    sa.CheckConstraint('spent_cents >= 0', name=op.f('ck_projects_spent_nonnegative')),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_projects_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('share_token', name=op.f('uq_projects_share_token'))
    )
    op.create_index('ix_projects_owner_updated', 'projects', ['owner_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_owner_updated', table_name='projects')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
