"""m5: renders

Revision ID: 96336d64c308
Revises: 4fb3d28300ef
Create Date: 2026-09-04 08:43:54.737298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '96336d64c308'
down_revision: Union[str, Sequence[str], None] = '4fb3d28300ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('renders',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('profile', sa.Enum('preview', 'final', name='render_profile'), nullable=False),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timeline_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('video_asset_id', sa.Uuid(), nullable=True),
    sa.Column('poster_asset_id', sa.Uuid(), nullable=True),
    sa.Column('subtitle_asset_id', sa.Uuid(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['poster_asset_id'], ['assets.id'], name=op.f('fk_renders_poster_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_renders_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subtitle_asset_id'], ['assets.id'], name=op.f('fk_renders_subtitle_asset_id_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_asset_id'], ['assets.id'], name=op.f('fk_renders_video_asset_id_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_renders'))
    )
    op.create_index('ix_renders_project_created', 'renders', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_renders_project_created', table_name='renders')
    op.drop_table('renders')
    # ### end Alembic commands ###
