"""m3: multi-user auth, content schema, jobs

Revision ID: a2fa00deff17
Revises: 7d49906e4c14
Create Date: 2026-09-04 07:49:42.549974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2fa00deff17'
down_revision: Union[str, Sequence[str], None] = '7d49906e4c14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('appearance', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('appearance_prompt', sa.Text(), nullable=False),
    sa.Column('voice', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('reference_asset_id', sa.Uuid(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_characters_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_characters')),
    sa.UniqueConstraint('project_id', 'slug', name='uq_characters_project_slug')
    )
    op.create_index(op.f('ix_characters_project_id'), 'characters', ['project_id'], unique=False)
    op.create_table('jobs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('parent_job_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'awaiting_provider', 'succeeded', 'failed', 'cancelled', 'skipped', name='job_status'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('message', sa.String(length=200), nullable=False),
    sa.Column('next_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_job_id'], ['jobs.id'], name=op.f('fk_jobs_parent_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_jobs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_jobs_idempotency_key'))
    )
    op.create_index('ix_jobs_active', 'jobs', ['status'], unique=False, postgresql_where="status IN ('queued','running','awaiting_provider')")
    op.create_index('ix_jobs_parent', 'jobs', ['parent_job_id'], unique=False)
    op.create_index('ix_jobs_project_queued', 'jobs', ['project_id', 'queued_at'], unique=False)
    op.create_table('locations',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prompt_fragment', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_locations_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('project_id', 'slug', name='uq_locations_project_slug')
    )
    op.create_index(op.f('ix_locations_project_id'), 'locations', ['project_id'], unique=False)
    op.create_table('story_inputs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_story_inputs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_inputs')),
    sa.UniqueConstraint('project_id', 'version', name='uq_story_inputs_project_version')
    )
    op.create_index(op.f('ix_story_inputs_project_id'), 'story_inputs', ['project_id'], unique=False)
    op.create_table('ai_calls',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('job_id', sa.Uuid(), nullable=True),
    sa.Column('capability', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('cost_cents', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_ai_calls_job_id_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ai_calls_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_calls'))
    )
    op.create_index('ix_ai_calls_project_created', 'ai_calls', ['project_id', 'created_at'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=12), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_events_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    op.create_index('ix_job_events_job_at', 'job_events', ['job_id', 'at'], unique=False)
    op.create_table('scenes',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('location_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('time_of_day', sa.String(length=16), nullable=False),
    sa.Column('mood', sa.String(length=120), nullable=False),
    sa.Column('present_slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_scenes_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_scenes_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenes'))
    )
    op.create_index('ix_scenes_project_order', 'scenes', ['project_id', 'sort_order'], unique=False)
    op.create_table('story_analyses',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('story_input_id', sa.Uuid(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('cost_cents', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('repaired', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_story_analyses_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_input_id'], ['story_inputs.id'], name=op.f('fk_story_analyses_story_input_id_story_inputs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_analyses'))
    )
    op.create_index(op.f('ix_story_analyses_project_id'), 'story_analyses', ['project_id'], unique=False)
    op.create_table('shots',
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('shot_type', sa.Enum('establishing', 'wide', 'medium', 'close_up', 'insert', 'over_shoulder', 'pov', name='shot_type'), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('composition_note', sa.Text(), nullable=False),
    sa.Column('camera_move', sa.Enum('static', 'push_in', 'pull_out', 'pan_left', 'pan_right', 'tilt_up', 'tilt_down', 'orbit', 'handheld', name='camera_move'), nullable=False),
    sa.Column('subject_motion', sa.Text(), nullable=False),
    sa.Column('ambient_sound', sa.String(length=120), nullable=False),
    sa.Column('motion_priority', sa.String(length=8), nullable=False),
    sa.Column('target_duration_s', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('motion_mode', sa.Enum('kenburns', 'generated', 'manual', name='motion_mode'), nullable=False),
    sa.Column('preferred_model_key', sa.String(length=64), nullable=True),
    sa.Column('subject_slugs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_override', sa.Text(), nullable=True),
    sa.Column('motion_override', sa.Text(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('selected_image_id', sa.Uuid(), nullable=True),
    sa.Column('selected_clip_id', sa.Uuid(), nullable=True),
    sa.Column('image_input_hash', sa.String(length=64), nullable=True),
    sa.Column('motion_input_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('target_duration_s BETWEEN 2.5 AND 12.0', name=op.f('ck_shots_target_duration_in_range')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_shots_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_shots_scene_id_scenes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shots'))
    )
    op.create_index('ix_shots_project_mode', 'shots', ['project_id', 'motion_mode'], unique=False)
    op.create_index('ix_shots_scene_order', 'shots', ['scene_id', 'sort_order'], unique=False)
    op.create_table('storyboards',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('story_analysis_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('cost_cents', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('repaired', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_storyboards_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_analysis_id'], ['story_analyses.id'], name=op.f('fk_storyboards_story_analysis_id_story_analyses'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storyboards')),
    sa.UniqueConstraint('project_id', 'version', name='uq_storyboards_project_version')
    )
    op.create_index(op.f('ix_storyboards_project_id'), 'storyboards', ['project_id'], unique=False)
    op.create_table('narration_lines',
    sa.Column('scene_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('shot_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('speaker_slug', sa.String(length=40), nullable=False),
    sa.Column('character_id', sa.Uuid(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('delivery', sa.String(length=16), nullable=False),
    sa.Column('audio_asset_id', sa.Uuid(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('input_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name=op.f('fk_narration_lines_character_id_characters'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_narration_lines_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.id'], name=op.f('fk_narration_lines_scene_id_scenes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], name=op.f('fk_narration_lines_shot_id_shots'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_narration_lines'))
    )
    op.create_index('ix_narration_scene_order', 'narration_lines', ['scene_id', 'sort_order'], unique=False)
    # Three-step so the change is safe against a table that already has rows:
    # add nullable, backfill, then enforce. Existing accounts get a sentinel
    # that no passphrase can ever hash to, so they are locked out rather than
    # silently given an empty credential -- create real accounts with
    # `make user-add`.
    op.add_column('users', sa.Column('passphrase_hash', sa.String(length=255),
                                     nullable=True))
    op.execute("UPDATE users SET passphrase_hash = 'disabled$no-login' "
               "WHERE passphrase_hash IS NULL")
    op.alter_column('users', 'passphrase_hash', nullable=False)
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False,
                                     server_default=sa.true()))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'passphrase_hash')
    op.drop_index('ix_narration_scene_order', table_name='narration_lines')
    op.drop_table('narration_lines')
    op.drop_index(op.f('ix_storyboards_project_id'), table_name='storyboards')
    op.drop_table('storyboards')
    op.drop_index('ix_shots_scene_order', table_name='shots')
    op.drop_index('ix_shots_project_mode', table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_story_analyses_project_id'), table_name='story_analyses')
    op.drop_table('story_analyses')
    op.drop_index('ix_scenes_project_order', table_name='scenes')
    op.drop_table('scenes')
    op.drop_index('ix_job_events_job_at', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index('ix_ai_calls_project_created', table_name='ai_calls')
    op.drop_table('ai_calls')
    op.drop_index(op.f('ix_story_inputs_project_id'), table_name='story_inputs')
    op.drop_table('story_inputs')
    op.drop_index(op.f('ix_locations_project_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index('ix_jobs_project_queued', table_name='jobs')
    op.drop_index('ix_jobs_parent', table_name='jobs')
    op.drop_index('ix_jobs_active', table_name='jobs', postgresql_where="status IN ('queued','running','awaiting_provider')")
    op.drop_table('jobs')
    op.drop_index(op.f('ix_characters_project_id'), table_name='characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
